// Shared "AI did something real, here" visual pattern, used everywhere a
// rule-based agent has touched what's on screen — never decorative. Every
// caller passes a status that reflects a real logged check/action; when
// nothing has run yet, callers must use "not_checked" rather than omitting
// the tag, so an absent badge is never mistaken for "nothing to see."
"use client";

import { useEffect, useState } from "react";
import { cn } from "@/lib/utils";
import { relativeTime } from "@/lib/format";

export type AiTagStatus = "checked" | "flagged" | "generated" | "not_checked";

const AI_TAG: Record<AiTagStatus, { label: string; text: string; bg: string }> = {
  checked: { label: "AI checked, no issues", text: "text-success", bg: "bg-success-soft" },
  flagged: { label: "AI flagged", text: "text-warning", bg: "bg-warning-soft" },
  generated: { label: "Generated by AI", text: "text-agent", bg: "bg-agent-soft" },
  not_checked: { label: "Not yet checked", text: "text-muted-foreground", bg: "bg-muted" },
};

/** The one shared "AI is active here" mark — a small purple pulsing dot, reused across every status. */
export function AiPulseDot({ className }: { className?: string }) {
  return (
    <span className={cn("relative inline-flex size-1.5 shrink-0", className)}>
      <span className="absolute inline-flex h-full w-full rounded-full bg-agent opacity-75 animate-ping" />
      <span className="relative inline-flex size-1.5 rounded-full bg-agent" />
    </span>
  );
}

export function AiTag({
  status,
  label,
  className,
}: {
  status: AiTagStatus;
  /** Override the default copy, e.g. "AI flagged — YOY_JUMP" */
  label?: string;
  className?: string;
}) {
  const cfg = AI_TAG[status];
  return (
    <span
      className={cn(
        "inline-flex items-center gap-1.5 rounded-full px-2 py-0.5 text-[11px] font-medium whitespace-nowrap",
        cfg.bg,
        cfg.text,
        className
      )}
    >
      <AiPulseDot />
      {label ?? cfg.label}
    </span>
  );
}

/** "Updated 4 minutes ago" — ticks forward on a client-side interval so it stays honest without a page refresh. */
export function LiveTimestamp({ date, prefix = "Updated" }: { date: Date; prefix?: string }) {
  const [, setTick] = useState(0);
  useEffect(() => {
    const id = setInterval(() => setTick((t) => t + 1), 30_000);
    return () => clearInterval(id);
  }, []);
  return (
    <span className="inline-flex items-center gap-1.5 text-[11px] text-muted-foreground">
      <AiPulseDot />
      {prefix} {relativeTime(date.toISOString())}
    </span>
  );
}
